register_data = {
    "email": "user@example.com",
    "first_name": "John",
    "last_name": "Doe",
    "password1": "123456",
    "password2": "123456"
}

request_meta = {'PATH': '/home/bekzod/.virtualenvs/p10-ecommerce-api/bin:/app/bin:/app/extensions/bin:/usr/bin',
                'container': 'flatpak', 'LC_MEASUREMENT': 'uz_UZ.UTF-8', 'XAUTHORITY': '/run/flatpak/Xauthority',
                'LC_TELEPHONE': 'uz_UZ.UTF-8', 'XMODIFIERS': '@im=ibus', 'GDMSESSION': 'cinnamon',
                'XDG_DATA_DIRS': '/app/share:/usr/share:/usr/share/runtime/share:/run/host/user-share:/run/host/share',
                'GTK_IM_MODULE': 'ibus', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/flatpak/bus',
                'PS1': '(p10-ecommerce-api) ',
                'XDG_CACHE_HOME': '/home/bekzod/.var/app/com.jetbrains.PyCharm-Professional/cache',
                'XDG_CURRENT_DESKTOP': 'X-Cinnamon',
                '__EGL_EXTERNAL_PLATFORM_CONFIG_DIRS': '/etc/egl/egl_external_platform.d:/usr/lib/x86_64-linux-gnu/GL/egl/egl_external_platform.d:/usr/share/egl/egl_external_platform.d',
                'LD_LIBRARY_PATH': '', 'LC_PAPER': 'uz_UZ.UTF-8',
                'SESSION_MANAGER': 'local/bekzod:@/tmp/.ICE-unix/1223,unix/bekzod:/tmp/.ICE-unix/1223',
                'LOGNAME': 'bekzod', 'ALSA_CONFIG_PATH': '/usr/share/alsa/alsa-flatpak.conf',
                'GST_PLUGIN_SYSTEM_PATH': '/app/lib/gstreamer-1.0:/usr/lib/extensions/gstreamer-1.0:/usr/lib/x86_64-linux-gnu/gstreamer-1.0',
                'PWD': '/home/bekzod/Projects/p10-ecommerce-api', 'PYCHARM_HOSTED': '1', 'LANGUAGE': 'en_US',
                'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG',
                'PYTHONPATH': '/home/bekzod/Projects/p10-ecommerce-api:/app/extra/plugins/python/helpers/pycharm_matplotlib_backend:/app/extra/plugins/python/helpers/pycharm_display',
                'SHELL': '/bin/sh', 'LC_ADDRESS': 'uz_UZ.UTF-8',
                'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/flatpak/exports/share/applications/com.jetbrains.PyCharm-Professional.desktop',
                'AT_SPI_BUS_ADDRESS': 'unix:path=/run/flatpak/at-spi-bus',
                'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GTK_MODULES': 'gail:atk-bridge',
                'VIRTUAL_ENV': '/home/bekzod/.virtualenvs/p10-ecommerce-api', 'CLUTTER_IM_MODULE': 'ibus',
                'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'ALSA_CONFIG_DIR': '/usr/share/alsa',
                'XDG_SESSION_DESKTOP': 'cinnamon', 'SHLVL': '0', 'LC_IDENTIFICATION': 'uz_UZ.UTF-8',
                'LC_MONETARY': 'uz_UZ.UTF-8', 'QT_IM_MODULE': 'ibus', 'PULSE_CLIENTCONFIG': '/run/flatpak/pulse/config',
                'XDG_CONFIG_DIRS': '/app/etc/xdg:/etc/xdg', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0',
                'LANG': 'en_US.UTF-8', 'XDG_SESSION_ID': 'c2', 'XDG_SESSION_TYPE': 'x11',
                'FLATPAK_SANDBOX_DIR': '/home/bekzod/.var/app/com.jetbrains.PyCharm-Professional/sandbox',
                'DISPLAY': ':99.0', 'GI_TYPELIB_PATH': '/app/lib/girepository-1.0', 'CINNAMON_VERSION': '5.6.8',
                'LC_NAME': 'uz_UZ.UTF-8', 'PYCHARM_DISPLAY_PORT': '63342', 'XDG_SESSION_CLASS': 'user',
                'FLATPAK_ID': 'com.jetbrains.PyCharm-Professional', 'GDM_LANG': 'en_US',
                'XDG_DATA_HOME': '/home/bekzod/.var/app/com.jetbrains.PyCharm-Professional/data',
                'GTK3_MODULES': 'xapp-gtk3-module', 'PYTHONIOENCODING': 'UTF-8',
                'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/bekzod', 'PYCHARM_JDK': '${FLATPAK_DEST}/extra/jbr/',
                'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'DESKTOP_SESSION': 'cinnamon',
                'USER': 'bekzod', 'XDG_CONFIG_HOME': '/home/bekzod/.var/app/com.jetbrains.PyCharm-Professional/config',
                'GIO_LAUNCHED_DESKTOP_FILE_PID': '2451', 'PULSE_SERVER': 'unix:/run/flatpak/pulse/native',
                'QT_ACCESSIBILITY': '1', 'LC_NUMERIC': 'uz_UZ.UTF-8', 'GJS_DEBUG_OUTPUT': 'stderr', 'XDG_SEAT': 'seat0',
                'SSH_AUTH_SOCK': '/run/flatpak/ssh-auth', 'DJANGO_SETTINGS_MODULE': 'config.settings',
                'PYTHONUNBUFFERED': '1', 'GTK_OVERLAY_SCROLLING': '1', 'QT_QPA_PLATFORMTHEME': 'qt5ct',
                'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_VTNR': '7', 'HOME': '/home/bekzod', 'DEBUG': 'True',
                'SECRET_KEY': 'django-insecure-9d7w9%q138s+iy-8&n4+n@loux#728b(otp&+swh_owo*=w43y',
                'DB_NAME': 'ecommerce_db', 'DB_USER': 'p10', 'DB_PASSWORD': '123', 'ALLOWED_HOSTS': '', 'TZ': 'UTC',
                'RUN_MAIN': 'true', 'SERVER_NAME': 'localhost', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '8000',
                'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1',
                'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/users/profile/',
                'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain',
                'HTTP_AUTHORIZATION': 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjgzMTE5OTk4LCJpYXQiOjE2ODMxMTk2OTgsImp0aSI6IjhiMDM5MjM1YTBlODRiNWVhYTI0OGUxMzlhYzczZDZlIiwidXNlcl9pZCI6OH0.9P3ouDfy89SyrWgHek-t-4XJImHhtPCrSBTbR83Fw3M',
                'HTTP_USER_AGENT': 'PostmanRuntime/7.32.2', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache',
                'HTTP_POSTMAN_TOKEN': '7af68529-db14-4fbb-86cb-fdf3d05b1fc1', 'HTTP_HOST': 'localhost:8000',
                'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive', 'wsgi.input': ''}
