# Generated by Django 4.2 on 2023-05-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='prize',
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
